HUMAN_STR = 5
HUMAN_INIT = 5
HUMAN_X = 9
HUMAN_Y = 9
HUMAN_CHAR = 'H'
HUMAN_NAME = "HUMAN"
HUMAN_ABILITY_COOLDOWN = 0
HUMAN_ABILITY_LAST_TIME = 0

WORLDWIDTH = 20
WORLDHEIGHT = 20

BREEDCOOLDOWN = 10

STARTINGWOLF = 3
WOLFINITIATIVE = 5
WOLFSTR = 9
WOLFCHAR = 'W'
WOLFFULLNAME = "WOLF"

STARTINGSHEEP = 3
SHEEPINITIATIVE = 4
SHEEPSTR = 4
SHEEPCHAR = 'S'
SHEEPFULLNAME = "SHEEP"

STARTINGCYBERSHEEP = 3
CYBERSHEEPINITIATIVE = 4
CYBERSHEEPSTR = 11
CYBERSHEEPCHAR = 'C'
CYBERSHEEPFULLNAME = "CYBERSHEEP"

STARTINGFOX = 3
FOXINITIATIVE = 7
FOXSTR = 3
FOXCHAR = 'F'
FOXFULLNAME = "FOX"

STARTINGANTELOPE = 3
ANTELOPEINITIATIVE = 5
ANTELOPESTR = 4
ANTELOPECHAR = 'A'
ANTELOPEFULLNAME = "ANTELOPE"

STARTINGTURTLE = 3
TURTLEINITIATIVE = 1
TURTLESTR = 2
TURTLECHAR = 'T'
TURTLEFULLNAME = "TURTLE"
TURTLEDEFLECTIONTRESHOLD = 5

STARTINGGRASS = 3
GRASSSTR = 0
GRASSCHAR = '.'
GRASSFULLNAME = "GRASS"

STARTINGPINE = 3
PINEBORSCHSTR = 10
PINEBORSCHCHAR = 'P'
PINEBORSCHFULLNAME = "PINEBORSCH"

STARTINGNIGHTSHADE = 3
NIGHTSHADESTR = 99
NIGHTSHADECHAR = 'N'
NIGHTSHADEFULLNAME = "NIGHTSHADE"

STARTINGDANDELION = 3
DANDELIONSTR = 0
DANDELIONCHAR = 'D'
DANDELIONFULLNAME = "DANDELION"

STARTINGGUARANA = 3
GUARANASTR = 0
GUARANACHAR = 'G'
GUARANAFULLNAME = "GUARANA"
